### PR TITLE
add bower registry

### PR DESCRIPTION
**Pull request by sparksm**
bower install jeditable

### CODE REVIEW

**Comment by holtkamp** [comment]
:+1: , someone still monitoring this repo?

**Comment by NicolasCARPi** [comment]
Hello,

I'm the new maintainer of this repository.

It is now 2017 and bower is not so trendy anymore. Everyone uses npm/yarn so I'm not sure if adding a bower.json is really a thing to do. Tell me what you think.

Thank you for your contribution :)

~Nico

**Comment by sparksm** [comment]
lol.  no one uses jquery either. this PR is from 2014 so do whatever you want.

**Comment by NicolasCARPi** [comment]
Ahah :)

**Pull request closed without merging**
